apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "red-pool"
spec:
  allowFirstLastIPs: 'No'
  blocks:
  - start: "172.16.0.1"
    stop: "172.16.0.254"
  - start: "2600:6c46:4600:3c20::2"
    stop:  "2600:6c46:4600:3c20:FFFF:FFFF:FFFF:FFFE"
  serviceSelector:
    matchExpressions:
      - {key: color, operator: NotIn, values: [blue]}
#    matchLabels:
#      color: red
