default_keys: &default_keys >-
  age1ldd7095er2v9wtw5qg02m37ylcyu706m387hjwvyqt3k035a35dqhnfaur,
  age1j0sn0kh9r0f0cj8553tjkz8w4rhhedzxdlwrqzy23dk7nhvn8ckqv50jvg,
  age1ff7vddme9s5gufe9lcyl5fhs0awfkkm0jun22yr5eamwxyca3cpqhy5xte
creation_rules:
- path_regex: 'gitea/values.yaml'
  encrypted_regex: 'password|Password'
  age: *default_keys
- path_regex: 'woodpecker/values.yaml'
  encrypted_regex: 'SECRET'
  age: *default_keys
- path_regex: 'cert-manager/secret.yml'
  encrypted_regex: 'key'
  age: *default_keys
- path_regex: 'pve.json|bootstrap.json'
  encrypted_regex: 'secret|token_id|.*pass'
  age: *default_keys
- path_regex: 'base-terraform/state.tf.json'
  encrypted_regex: 'secret_key'
  age: *default_keys
