apiVersion: v1
kind: Pod
metadata:
  name: explore
  labels:
    pod-security.kubernetes.io/enforce: privileged
spec:
  containers:
  - name: nginx-container
    image: python
    command:
      - sleep
      - infinity
    volumeMounts:
    - name: host
      mountPath: /host
  volumes:
  - name: host
    hostPath:
      path: /var
      type: Directory

