apiVersion: v1
kind: Pod
metadata:
  name: explore
  annotations:
    securityContext.allowPrivilegeEscalation: 'false'
spec:
  containers:
  - name: nginx-container
    image: python
    command:
      - sleep
      - infinity
#    volumeMounts:
#    - name: host
#      mountPath: /host
#  volumes:
#  - name: host
#    hostPath:
#      path: /var
#      type: Directory

