apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostport-pod
  labels:
    pod-security.kubernetes.io/enforce: privileged
spec:
  containers:
  - name: nginx-container
    image: python
    command:
      - python3
      - -m
      - http.server
      - '80'
    ports:
      - containerPort: 80    # The container listens on port 80
        hostPort: 80         # Expose port 80 on the host
        protocol: TCP

